### ISSUE TITLE
How to use .QueryRow ?

### ISSUE THREAD

**Issue by taophp** [infogulch/xtemplate#25]
I had a bad afternoon trying to get  `.QueryRow` to work the way I wanted:
```
{{define "GET /posts/{slug}"}}
  {{ $slug := .Req.PathValue "slug" }}
  {{ $query := printf "SELECT title FROM posts WHERE slug='%s'" $slug }}
  {{ $result := .DB.QueryRow $query }}
  {{ $result.title}}
{{end}}
```
That's not so bad, but not so good either. The fact is that doing things this way lead to SQL injections, obviously. I may sanitize `$slug` before using it, but that's risky, painful, and should not be done at this level. I dove into the code of xtemplate-caddy, xtemplate, and sample apps (todo and rss) to pick some snippets, but none worked. One example, the one that should work as I see it:
```
{{define "GET /posts/{slug}"}}
  {{ $slug := .Req.PathValue "slug" }}
  {{ $result := .DB.QueryRow `SELECT title FROM posts WHERE slug = '?'` $slug }}
  {{ $result.title }}
{{end}}
```
But I get this error:
```
web-1    | {"level":"warn","ts":1728505670.0116303,"msg":"error executing template","xtemplate-caddy":{"xtemplate":{"instance":43,"serve":{"requestid":"13dd450d-2894-4c57-b598-186e963050aa"},"error":"template: /posts.html:16:19: executing \"GET /posts/{slug}\" at <.DB.QueryRow>: error calling QueryRow: expected 0 arguments, got 1"}}}
```
Which is very curious to my eyes:
1. if `.QueryRow` does not accept any arguments, you can only inject variables in a string before passing it (like I did) and be vulnerable to SQL injections,
2. in the code I read from sample applications,  I'm sure that there is cases where `.QueryRow` is used with arguments.

Unsurprisingly, I got the same result with:
```
{{ $result := .DB.QueryRow `SELECT title FROM posts WHERE slug = '$1'` $slug }}
{{ $result := .DB.QueryRow `SELECT title FROM posts WHERE slug = '%s'` $slug }}
{{ $result := .DB.QueryRow `SELECT title FROM posts WHERE slug = '$1'` (.Req.PathValue "slug") }}
{{ $result := .DB.QueryRow `SELECT title FROM posts WHERE slug = '?'` (.Req.PathValue "slug") }}
```
Am I doing something wrong ?

**Comment by infogulch** [comment]
I was confused for a moment because your last examples are how I intended for it to be used. You can see in the code where [QueryRow accepts parameters](https://github.com/infogulch/xtemplate/blob/a7eea622232e20fe09e481e88f7991c0c053de12/providers/db.go#L90-L94).

If you look at the `🔱 Add custom routes to handle any method and path pattern` feature example in the readme you may notice a detail that I think could give you a hint:

```html
<!-- match on path parameters -->
{{define "GET /contact/{id}"}}
{{$contact := .QueryRow `SELECT name,phone FROM contacts WHERE id=?` (.Req.PathValue "id")}}
<div>
  <span>Name: {{$contact.name}}</span>
  <span>Phone: {{$contact.phone}}</span>
</div>
{{end}}
```

Note, it's written `WHERE id=?` not `WHERE id='?'`.

I suspect the last part of your error is actually coming from the database itself...

> error calling QueryRow: *expected 0 arguments, got 1*

... because the database sees `'?'` as a *string* that contains a question mark, rather than a query parameter.

So you should be able to fix it by removing the quotes from the parameters. To remember, maybe it would be helpful to think about how the query syntax could differentiate between a quoted string and a query parameter if params were quoted.

---

I could make the error message better to make it more clear when an error is originating from the database rather than the template system.

Also I'm aware that the examples are very sparse, sorry about that.

**Comment by taophp** [comment]
Thanks for your answer.
The fact is that I tried without quotes at my first attempt, and added them to deal with another error... So, let's rewind !

With:
```
{{define "GET /posts/{slug}"}}
  {{ $slug := .Req.PathValue "slug" }}
  {{ $result := .DB.QueryRow `SELECT title FROM posts WHERE slug = ?` $slug }}
  {{ $result.title }}
{{end}}
```
I get this log:
```
web-1    | {"level":"debug","ts":1728543273.9301999,"msg":"serving request","xtemplate-caddy":{"xtemplate":{"instance":3,"serve":{"requestid":"cc9ccc0a-5613-4a9f-9fab-8de6318cccd6"},"user-agent":"curl/8.9.1","method":"GET","requestPath":"/posts/test-slug"}}}
db-1     | 2024-10-10 06:54:33.930 UTC [35] ERROR:  syntax error at end of input at character 46
db-1     | 2024-10-10 06:54:33.930 UTC [35] STATEMENT:  SELECT title FROM public.posts WHERE slug = ?
web-1    | {"level":"debug","ts":1728543273.9308023,"msg":"QueryRows","xtemplate-caddy":{"xtemplate":{"instance":3,"serve":{"requestid":"cc9ccc0a-5613-4a9f-9fab-8de6318cccd6"},"query":"SELECT title FROM public.posts WHERE slug = ?","params":["test-slug"],"error":"ERROR: syntax error at end of input (SQLSTATE 42601)","queryduration":0.000223259}}}
web-1    | {"level":"warn","ts":1728543273.931147,"msg":"error executing template","xtemplate-caddy":{"xtemplate":{"instance":3,"serve":{"requestid":"cc9ccc0a-5613-4a9f-9fab-8de6318cccd6"},"error":"template: /index.html:4:19: executing \"GET /posts/{slug}\" at <.DB.QueryRow>: error calling QueryRow: ERROR: syntax error at end of input (SQLSTATE 42601)"}}}
```
I tried to add quotes this way:
```
{{ $slug := print "'" (.Req.PathValue "slug") "'"}}
```
But get nearly the same thing, with quotes added where expected.

I did not mention that I use PostgreSQL. I know that you usually use SQLite. Can this be related ?
If you want to try in my context, the project is here: https://github.com/PixyBlue/lazy-lob-web
You don't need to make a new project to run the sample app contrary to what is written in the how to start, just follow this steps (if you have the [`just`](https://just.systems) command available - recommanded):
```
git clone https://github.com/PixyBlue/lazy-lob-web
cd lazy-lob-web
just build
just boot
just init # or just init-dev to install localhost certificates, but rely on sudo
just open # open your browser on https://localhost
```
Alternatively, if you cannot use `just`:
```
git clone https://github.com/PixyBlue/lazy-lob-web
cd lazy-lob-web
docker compose build
docker compose up &
docker compose exec web dbmate up
docker compose exec web migrate
```

**Comment by infogulch** [comment]
> I did not mention that I use PostgreSQL. I know that you usually use SQLite. Can this be related ?

Yes, the parameter syntax is specific to the database. (This may be worth mentioning somewhere...)

For pgsql parameters are named with `$1`, `$2`, `$3` etc [^1][^2] based on the parameter's position. So in your case I'd expect this to work:

```
{{define "GET /posts/{slug}"}}
  {{ .DB.QueryValue `SELECT title FROM posts WHERE slug = $1` (.Req.PathValue "slug") }}
{{end}}
```

(I cheated and used .QueryValue since you're only returning one column. 😄)

[^1]: https://minervadb.xyz/how-parameterized-queries-and-bind-parameters-are-implemented-in-postgresql/
[^2]: https://www.postgresql.org/docs/current/sql-prepare.html

**Comment by taophp** [comment]
It works! Thanks for your help!
