### ISSUE TITLE
Feature request: how to handle translations ?

### ISSUE THREAD

**Issue by taophp** [infogulch/xtemplate#4]
Currently, I see no easy, obvious way to handle T10N within xtemplate. And I don't think any ambitious web site or app should avoid this nowadays. So I'm sharing my thoughts about it below. Please, let me know what you think.

- T10N should not be handled by the client as it would heavily impact the performance of the app;
- xtemplate should decide which T10N to use based on the [browser preferred languages](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language) ; the user should be able to change this language using some UI switch that should overwrite the browser's one along the session (using dedicated cookie? request parameter?) ; the switch itself should be the responsibility of app developer, but the best practice to handle T10N during user's session should be documented;
- there is mainly three sources of contents that should be translated in xtemplate: templates themselves, databases, and markdown content files;
- regarding markdown content files: there should be different directories, one for each languages supported by the app; for the Caddy plugin, these directories should be pointed by context configuration, something like:
```
context {
  path: <string> # content path, which contains languages directories if translations activated
  fallback2default: <bool> # if true, content unavailable in requested T10N will be replaced by the default language content; if false, unavailable content in requested T10N will raised a 404 error; `true` by default
  default-language: EN # define the language of the default path, may be optional and EN by default 
  translations {
      FR: <string> # path for the french T10N (may we go deeper and handle L18N ? FR-fr, FR-ca ?)
      DE: <string> # path for the german T10N
  }
}
```
A default directory structure like this one below should be proposed, actionable with a simple configuration:
The default translated directory tree:
```
<path>
├── DE
├── EN
├── FR
└── ...
```
And then, a simple configuration with T10N should be
```
context {
  path: <string>
  translations
}
```
- regarding templates, a new, easily callable, translation function should be added (maybe classically named `_` or `t_`), that handles string with arguments ; translated strings should be stored in files, something compatible with [Weblate](https://weblate.org), maybe [go-i18n JSON files](https://docs.weblate.org/en/latest/formats/go-i18n.html) or [gotext JSON files](https://docs.weblate.org/en/latest/formats/gotext.html); T10N files should live in a default directory, maybe configurable;
- regarding db contents: well, it is  the responsibility of the developer to use dedicated columns and/or tables; may be a recommended way should be documented somewhere; xtemplate should provide a dot context value to get the current language in queries.

**Comment by taophp** [comment]
@infogulch any thoughts about this?

**Comment by infogulch** [comment]
I agree that i18n is important and useful.

I doubt the utility of an imposed file structure specifically for translated documents. The described document selection design can be implemented entirely within the template language, and in fact this is how I envisioned xtemplate being used. Templates already have access to headers, cookies, parameters, etc, and can perform complex conditionals and control flow in order to select and render the appropriate document for a particular request. Perhaps a demo or example that shows how to use xtemplate to select different versions of documents would be a good fit for this repo.

As for string translation, I could see a custom dot provider that loads and can lookup translated strings from one or more of the mentioned file formats. Then configure it to use a field name like "T" and use it like `{{ .T.Tr "Sign up now for a discount!" }}`.

**Comment by taophp** [comment]
@infogulch Thanks. I'll let you know.
